### ISSUE TITLE
Use correct resource id while logging for audit

### ISSUE THREAD

**Issue by kailash** [datakaveri/iudx-gis-interface#86]
While creating the GIS entry, we are using the admin token and iid of the admin token as resource id, which is [rs.iudx.io], it is not available as catalog id. 
due to this metering APIs (summary API) will eventually fails.

**Resolution**:
use resource id from request.

**Comment by ankitmashu** [comment]
The id which is mention in body of create GIS entry is also not available  in catalogue, which will again leads to fail of metering extension api.

**Comment by kailash** [comment]
closed with #88, auditing flows are removed from GIS.
